GGames/Aplicacion/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name='index'),
    path('juegos/',views.juegos,name='juegos'),
    path('tarjetas/',views.tarjetas,name='tarJetas'),
    path('formulario/',views.formulario,name='formulario'),
    path('ju/',views.JuegoListView.as_view(),name='ju'),
    path('ju/<int:pk>',views.JuegoDetailView.as_view(),name='juego-detail'),
    path('compañia/<int:pk>',views.CompañiaDetailView.as_view(), name='compañia-detail'),
    path('compañia/',views.ComapñiaListView.as_view(),name='compañia'),
    path('genero/<int:pk>',views.GeneroDetailView.as_view(), name='genero-detail'),
    path('genero/',views.GeneroListView.as_view(),name='genero'),
]

urlpatterns+= [
    path('compañia/create/',views.CompañiaCreate.as_view(), name='compañia_create'),
    path('compañia/<int:pk>/delete/',views.CompañiaDelete.as_view(), name='compañia_delete'),
    path('compañia/<int:pk>/update/',views.CompañiaUpdate.as_view(), name='compañia_update'),

    path('ju/create/',views.JuegoCreate.as_view(), name='juego_create'),
    path('ju/<int:pk>/delete/',views.JuegoDelete.as_view(), name='juego_delete'),
    path('ju/<int:pk>/update/',views.JuegoUpdate.as_view(), name='juego_update'),

    path('genero/create/',views.GeneroCreate.as_view(), name='genero_create'),
    path('genero/<int:pk>/delete/',views.GeneroDelete.as_view(), name='genero_delete'),
    path('genero/<int:pk>/update/',views.GeneroUpdate.as_view(), name='genero_update'),
]

GGames/GGames/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from rest_framework import routers
from quick import views

router = routers.DefaultRouter()
router.register(r'api/users', views.UserViewSet)
router.register(r'api/groups', views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Aplicacion/', include('Aplicacion.urls')),
    path('accounts/',include('sesion.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',TemplateView.as_view(template_name='index.html'),name='index'),
]

urlpatterns += [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns+= static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

GGames/sesion/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

GGames/Aplicacion/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances

# Create your models here.
class Genero(models.Model):
	nombre_genero = models.CharField(max_length=200)
	
	def get_absolute_url(self):
		return reverse('genero-detail', args=[str(self.id)])

	def __str__(self):
		return self.nombre_genero

class Juego(models.Model):
    
	titulo = models.CharField(max_length=200)
	compañia = models.ForeignKey('Compañia', on_delete=models.SET_NULL, null=True)
    
	descirpcion = models.TextField(max_length=1000, help_text='Inserte una descripcion del juego')
	genero = models.ManyToManyField(Genero)

	def get_absolute_url(self):
		return reverse('juego-detail', args=[str(self.id)])
    
	def __str__(self):
		return self.titulo

class Compañia(models.Model):
	compañia = models.CharField(max_length=100)

	def get_absolute_url(self):
		return reverse('compañia-detail', args=[str(self.id)])

	def __str__(self):
		return self.compañia

GGames/quick/models.py
from django.db import models

# Create your models here.

GGames/Aplicacion/forms.py
from django import forms

from . models import Compañia

class CompañiaForm(forms.ModelForm):
    compañia = forms.CharField(label='Compañia',max_length=200, widget=forms.TextInput(
        attrs={
            'class':'form-control'
        }
    ))

    class Meta:
        model = Compañia
        fields = ('compañia',)

GGames/Aplicacion/views.py
from django.shortcuts import render
from . models import Genero,Juego,Compañia
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
def index(request):
    return render(
        request,"index.html")

def juegos(request):
    return render(
        request,"juegos.html")

def tarjetas(request):
    return render(
        request,"tarjetas.html")

def formulario(request):
    return render(
        request,"formulario.html")
        
#compañia
class CompañiaCreate(CreateView):
    model = Compañia
    fields = '__all__'

class CompañiaUpdate(UpdateView):
    model = Compañia
    fields = ['compañia']

class CompañiaDelete(DeleteView):
    model = Compañia
    success_url = reverse_lazy('index')

class CompañiaDetailView(generic.DetailView):
    model = Compañia 

class ComapñiaListView(generic.ListView):
    model=Compañia
    paginate=10

#Genero
class GeneroCreate(CreateView):
    model= Genero
    fields='__all__'

class GeneroUpdate(UpdateView):
    model = Genero
    fields = ['nombre_genero']

class GeneroDelete(DeleteView):
    model= Genero
    success_url = reverse_lazy('index')

class GeneroDetailView(generic.DetailView):
    model=Genero

class GeneroListView(generic.ListView):
    model=Genero
    paginate=10

#Juego

class JuegoListView(generic.ListView):
    model=Juego
    paginate=10

class JuegoCreate(CreateView):
    model= Juego
    fields='__all__'

class JuegoUpdate(UpdateView):
    model = Juego
    fields = ['titulo','compañia','descirpcion','genero']

class JuegoDelete(DeleteView):
    model= Juego
    success_url = reverse_lazy('index')

class JuegoDetailView(generic.DetailView):
    model=Juego

GGames/quick/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from quick.serializers import UserSerializer, GroupSerializer


# Create your views here.
class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

 

GGames/sesion/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

GGames/Aplicacion/templates/Aplicacion/compañia_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<section class="container" style="margin-left:20px ;">
    <article class="row">
        <div class="col-xs-12 col-sm-4 col-lg-12 col-xl-12">
            <h1>Borrar Compañia</h1>
            <p style="color: aliceblue;">Estas seguro que quieres eliminar la compañia :{{compañia}} </p>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" action="" value="Si, Borrar">
            </form>
        </div>
        
    </article>
    

    
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/compañia_detail.html
{% extends "base_generic.html" %}

{% block content%}

<section>
    <article class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        <h1>compañia: {{compañia}}</h1>
        {% if user.is_authenticated  %}{% if user.is_staff %}
        <div class="conteiner-fluid">
            <div class="row">
                <div class="btn-group col-xs-12 col-sm-4 col-lg-4 col-xl-4">
                    <a class="btn btn-block funti" href="{% url 'compañia_update' pk=compañia.pk %}" 
                    style="background-color: #581845c2; margin: 0px; font-size: 16px; font-family: Prisma; color: #ffffff;border-color: black;">
                    Actualizar</a>
                    <a class="btn btn-block funti" href="{% url 'compañia_delete' pk=compañia.pk %}" 
                    style="background-color: #581845c2; margin: 0px; font-size: 16px; font-family: Prisma; color: #ffffff; border-color: black;">
                    Eliminar</a>
                    
                </div>
            </div>
        </div>
        {% else %}{% endif %}{% else %}{% endif %}
    </article>
    <article>
        <div style="margin-left:20 px;margin-top: 20px;" class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        <h4 style="color: aliceblue;">Juegos</h4>
            <dl>
                {%for juego in compañia.juego_set.all%}
                    <dt><a href="{% url 'juego-detail' pk=juego.pk %}">{{juego}}</a>
                        {{juego.juegoinstance_set.all.count}}</dt>
                        <dd style="color: #ffffff;">{{juego.descirpcion}}</dd>
                {%endfor%}
            </dl>
        </div>
    </article>
</section>
{%endblock%}

GGames/Aplicacion/templates/Aplicacion/compañia_form.html
{% extends "base_generic.html" %}

{% block content %}
<section class="container" style="margin-left: 20px;">
    <article class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
            <h1>Creacion de Compañia</h1>
        </div>
    </article>
    <article class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
            <form action ="" method="post">
                {% csrf_token %}
                <table style="color: aliceblue;">
                    {{form.as_table}}
                </table>
                <input type="submit" value="Enviar">
            </form>
        </div>
        
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/compañia_list.html
{% extends "base_generic.html" %}
{% block content %}
<section>
    <article class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        <h1>Lista de Compañias</h1>
    </article>
    <article class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        {% if compañia_list %}
        <ul>
            {% for compañia in compañia_list %}
            <div>
                <li style="color: aliceblue;">
                    <a href="{{ compañia.get_absolute_url }}" >{{compañia.compañia}}</a>
                </li>
            </div>
            {% endfor %}
            
        </ul>
        {% else %}
            <p>No hay Compañias disponible</p>
        {% endif %}
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/genero_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<section class="container" style="margin-left:20px ;">
    <article class="row">
        <div class="col-xs-12 col-sm-4 col-lg-12 col-xl-12">
            <h1>Borrar Genero</h1>
            <p style="color: aliceblue;">Estas seguro que quieres eliminar la compañia :{{genero}} </p>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" action="" value="Si, Borrar">
            </form>
        </div>
        
    </article>
    

   
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/genero_detail.html
{% extends "base_generic.html" %}

{% block content%}
<section>
    <article class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        <h1>Genero: {{genero}}</h1>
        {% if user.is_authenticated  %}{% if user.is_staff %}
        <div class="conteiner-fluid">
            <div class="row">
                <div class="btn-group col-xs-12 col-sm-12 col-lg-12 col-xl-12">
                    <a class="btn btn-block" href="{% url 'genero_update' pk=genero.pk %}" 
                    style="background-color: #581845c2; margin: 0px;  font-family: Prisma; color: #ffffff;border-color: black;">
                    Actualizar</a>
                    <a class="btn btn-block" href="{% url 'genero_delete' pk=genero.pk %}" 
                    style="background-color: #581845c2; margin: 0px;  font-family: Prisma; color: #ffffff; border-color: black;">
                    Eliminar</a>
                    
                </div>
            </div>
        </div>
        {% else %}{% endif %}{% else %}{% endif %}
    </article>
</section>
{%endblock%}

GGames/Aplicacion/templates/Aplicacion/genero_form.html
{% extends "base_generic.html" %}

{% block content %}
<section class="container" style="margin-left: 20px;">
    <article class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
            <h1>Creacion de Genero</h1>
        </div>
    </article>
    <article class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
            <form action ="" method="post">
                {% csrf_token %}
                <table style="color: aliceblue;">
                    {{form.as_table}}
                </table>
                <input type="submit" value="Enviar">
            </form>
        </div>
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/genero_list.html
{% extends "base_generic.html" %}
{% block content %}
<section>
    <article class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        <h1>Lista de Generos</h1>
    </article>
    <article class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        {% if genero_list %}
        <ul>
            {% for genero in genero_list %}
            <div>
                <li style="color: aliceblue;">
                    <a href="{{ genero.get_absolute_url }}" >{{genero.nombre_genero}}</a>
                </li>
            </div>
            {% endfor %}
            
        </ul>
        {% else %}
            <p>No hay Generos disponible</p>
        {% endif %}
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/juego_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<section class="container" style="margin-left:20px ;">
    <article class="row">
        <div class="col-xs-12 col-sm-4 col-lg-12 col-xl-12">
            <h1>Borrar Juego</h1>
            <p style="color: aliceblue;">Estas seguro que quieres eliminar la compañia :{{juego}} </p>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" action="" value="Si, Borrar">
            </form>
        </div>
        
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/juego_detail.html
{% extends "base_generic.html" %}

{% block content %}
<section>
    <article class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
        <h1>Titulo: {{ juego.titulo }}</h1>
        <div>
            <p style="color: aliceblue;"><strong style="color: aliceblue;">Compañia:</strong> <a href="{% url 'compañia-detail' pk=juego.compañia.pk%}">{{ juego.compañia }}</a></p>
            <p style="color: aliceblue;"><strong style="color: aliceblue;">Descripcion:</strong> {{ juego.descirpcion }}</p>
            <p style="color: aliceblue;"><strong style="color: aliceblue;">Genero:</strong> {% for genero in juego.genero.all %} {{ genero }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  
        </div>
        {% if user.is_authenticated  %}{% if user.is_staff %}
        <div class="conteiner-fluid">
            <div class="row">
                <div class="btn-group col-xs-12 col-sm-4 col-lg-4 col-xl-4">
                    <a class="btn btn-block" href="{% url 'juego_update' pk=juego.pk %}" 
                    style="background-color: #581845c2; margin: 0px;  font-family: Prisma; color: #ffffff;border-color: black;">
                    Actualizar</a>
                    <a class="btn btn-block" href="{% url 'juego_delete' pk=juego.pk %}" 
                    style="background-color: #581845c2; margin: 0px;  font-family: Prisma; color: #ffffff; border-color: black;">
                    Eliminar</a>
                    
                </div>
            </div>
        </div>
        {% else %}{% endif %}{% else %}{% endif %}
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/juego_form.html
{% extends "base_generic.html" %}

{% block content %}
<section class="conteiner-fluid">
    <article class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12 col-xl-12" style="margin-left: 10px;">
            <h1>Creacion de Juego</h1>
        </div>
    </article>
    <article class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12 col-xl-12" style="margin-left: 10px;">
            <form action ="" method="post">
                {% csrf_token %}
                <table style="color: aliceblue;">
                    {{form.as_table}}
                </table>
                <input type="submit" value="Enviar">
    
            </form>
        </div>
        
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/Aplicacion/juego_list.html
{% extends "base_generic.html" %}
{% block content %}
<section>
    <article>
        <h1>Lista de Juegos</h1>
    </article>
    <article>
        {% if juego_list %}
        <ul>
            {% for juego in juego_list %}
            <div>
                <li style="color: aliceblue;">
                    <a href="{{ juego.get_absolute_url }}" >{{juego.titulo}}</a>({{juego.compañia}})
                </li>
            </div>
            {% endfor %}
            
        </ul>
        {% else %}
            <p>No hay Juegos disponible</p>
        {% endif %}
    </article>
</section>
{% endblock %}

GGames/Aplicacion/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>GGames</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="styleSheet" type="text/css" href="{% static 'css/estilos_inicio.css' %}">
    <link rel="styleSheet" type="text/css" href="{% static 'css/estilos_juegos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos_Formularios.css' %}" >
    <link rel="styleSheet" type="text/css" href="{% static 'css/tarjetas.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/Validacion.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <!--Menu-->
    <header class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12 col-xl-12">
          <nav  id="menu" class="navbar navbar-expand-sm navbar-dark">
            <a href="{% url 'index' %}" class="navbar-brand"><img src="{% static 'images/icono_recortado.jpeg' %}" alt="Icono Pagina"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#uno">
              <span  class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="uno" >
              <ul class="navbar-nav">
                <li class="nav-item"><a href="{% url 'index' %}" class="nav-link">Inicio</a></li>
                <li class="nav-item"><a href="{% url 'juegos' %}" class="nav-link">Juegos</a></li>
                <li class="nav-item"><a href="{% url 'tarJetas' %}" class="nav-link">Tarjetas de regalo</a></li>
                
                {% if user.is_authenticated  %}
                <li style="background-color: #581845c2;" li class="nav-item" >
                  <a class="nav-link alerta" href="{% url 'logout' %}" id="P"> Cerrar sesión </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'password_reset' %}" class="nav-link">Reiniciar Password</a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Funciones
                  </a>
                  <div class="dropdown-menu" style="background-color: #581845c2;">
                    <a href="{% url 'ju' %}" class="dropdown-item nav-link">Lista de Juegos</a>
                    <a class="dropdown-item nav-link" href="{% url 'juego_create' %}">Agregar Juego</a>
                    <a class="dropdown-item nav-link" href="{% url 'compañia' %}">Lista Compañias</a>
                    <a class="dropdown-item nav-link" href="{% url 'compañia_create' %}">Agregar Compañia</a>
                    <a class="dropdown-item nav-link" href="{% url 'genero' %}">Lista Generos</a>
                    <a class="dropdown-item nav-link" href="{% url 'genero_create' %}">Agregar Genero</a>
                  </div>
                {% else %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    Funciones
                  </a>
                  <div class="dropdown-menu" style="background-color: #581845c2;">
                    <a href="{% url 'ju' %}" class="dropdown-item nav-link">Lista de Juegos</a>
                    <a class="dropdown-item nav-link" href="{% url 'compañia' %}">Lista Compañias</a>
                    <a class="dropdown-item nav-link" href="{% url 'genero' %}">Lista Generos</a>
                  </div>
                {% endif %}
                {% else %}
                <li style="background-color: #581845c2;" li class="nav-item">
                  <a class="nav-link alerta" href="{% url 'login' %}" id="P"> Ingresar </a>
                </li>
                
                {% endif %}
            </div>
          </nav>
        </div>
      </div>
    </header>
    {% block content %}{% endblock %}
    <footer class="container-fluid">
      <div class="row">
        <div class="d-none d-md-block col-md-6 col-lg-6 col-xl-6 text-left">
          <img id="metodo" src="{% static 'images/metodo_pago5.png' %}" class="img-fluid" alt="">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 text-right">
          <h6 class="text-muted lead">Nuestras Redes</h6>
          <div id="pie" class="redes-footer">
            <a href="https://www.instagram.com/jorge_whats_up/" target="_blank"><img src="{% static 'images/instagram_logo.png' %}" alt="Instagram_Jorge"></a>
            <a href="https://www.instagram.com/ke.vin__.sky/" target="_blank"><img src="{% static 'images/instagram_logo.png' %}" alt="Instagram_Kevin"></a>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-right">
          <p class="text-muted small">Kevin San Martin & Jorge Meneses @2020.<br> Todos los derechos reservados.</p>
        </div>
      </div>
    </footer>
  </body>
</html>  
    
      

GGames/Aplicacion/templates/formulario.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
    <body>
        <section id="Forma" class="container-fluid">
            <article>
                <div class="row">
                    <div  class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <form id="mi-formulario" action="index.html" >
                            
                            <label>Nombres: </label>
                            <input type="text" name="nombre" minlength="2" required>

                            <label>Apellidos: </label>
                            <input type="text" name="apellido" minlength="2" required>
                            
                            <label>Correo Electrónico: </label>
                            <input type="text" name="email" required placeholder="nombre@dominio.cl">
                        
                            <label>Telefono: </label>
                            <input type="text" name="fono" minlength="9" required>
                        
                            <label>Fecha Nacimiento: </label>
                            <input type="date" name="fecha" min="1900-01-01" required>

                            <button id="btn1" >Enviar</button>
                        </form>
                    </div>
                </div>
            </article>
        </section>
        <div id="osito"><img src="{% static 'images/prob.png' %}"></img></div> 

        <div id="proble"><button id="prob">Problemas!?</button>
            <p>Contactanos a este número: +569 5119 8112</p>
        </div>
    </body>
{% endblock %}

GGames/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/Validacion.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block title %}<title>GGames</title>{% endblock %}
</head>  
</style>
<body>
{% block content %}{% endblock %}
</body>
</html>

GGames/templates/home.html
{% extends 'base_generic.html' %}

{% block content %}
<section>
  <div class="container">
      <div>
        <h1 id="titulo">GGames</h1>
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-4 col-lg-12 col-xl-12">
            <p style="color: aliceblue;">Bienbenido a <em>GGames</em>, Django website </p>
            {% if user.is_authenticated %}
              <h3 style="color: aliceblue;">Hola! {{ user.username }}</h3>
            {% else %}
              <p style="color: aliceblue;">Tu no estas Registrado</p>
              <a href="{% url 'login' %}">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
  </div>
</section>
{% endblock %}

GGames/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="post" class="formulario rounded px-5">
    <div class="text-center mb-4">
        <img class="mb-4"src="{% static 'images/logo.png' %}" alt="" width="90" height="90">
        <h1 class="titulo mb-3 font-weight-bold">GGames</h1>
        <p class="text-light">Registrece para poder acceder a todo nuestro contenido</p>
    </div>
    {% csrf_token %}
    <div class="formulario-label">
        <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
        <label for="usuario">Ingrese Usuario</label>       
    </div>
    <div class="formulario-label">
      <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
        <label for="pass">Ingrese Password</label>  
    </div>
    
    <div class="formulario-label">
      <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
        <label for="pass">confirme Password</label>  
    </div>  

    <button type="submit" class="btn btn-danger btn-block">Registrar</button>
    <p class="mt-5 mb-3 text-muted text-center">&copy; GGames-2020</p>
</form>
{% endblock %}